import './globals.css'
import type { Metadata } from 'next'
import localFont from 'next/font/local'

export const metadata: Metadata = {
  title: 'Apple TV+ - Apple',
  description: 'Generated by create next app',
}


const sfFontRegular = localFont({ src: '../public/fonts/SF-Pro-Display-Regular.woff' })


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${sfFontRegular.className} bg-gray-950`}>
        {children}
      </body>
    </html>
  )
}
